preconfiguration: &preconfiguration
  working_directory: /druid
  docker:
    - image: google/cloud-sdk:latest


version: 2
jobs:
  build:
    <<: *preconfiguration
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t druid .
            mkdir -p caches
            docker save -o caches/druid.tar druid
      - persist_to_workspace:
          root: caches
          paths: 
            - druid.tar
  master-deploy:
    <<: *preconfiguration
    steps:
      - attach_workspace:
          at: /druid/caches
      - deploy:
          name: Tag master and deploy
          command: |
            set +o pipefail
            docker load -i /druid/caches/druid.tar | true
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GCLOUD_PROJECT
            docker tag app:latest gcr.io/${GCLOUD_PROJECT}/druid-docker:latest
            gcloud docker -- push gcr.io/${GCLOUD_PROJECT}/druid-docker:latest
workflows:
  version: 2
  master-build-n-deploy:
    jobs:
      - build
      - master-deploy:
          requires:
            - build
