apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: druid
    component: druid-historical
  name: druid-historical
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: druid
        component: druid-historical
    spec:
      containers:
      - name: druid-historical
        image: gcr.io/stream-150408/druid-historical:0.9.1.1-27
        ports:
        - containerPort: 8084
        env:
          - name: ZOOKEEPER_SERVER
            value: kafka-zoo-svc:2181
          - name: PSQL_SERVER
            value: postgresql
          - name: PSQL_USER
            value: "druid"
          - name: PSQL_PASSWORD
            value: "druid"
          - name: MEMCACHED_SERVER
            value: memcached-1-svc:11211
          - name: DRUID_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: S3_BUCKET
            value: "zz-kubernetes-test"
          - name: S3_ACCESS_KEY
            value: "AKIAJ6QLN3VWWNK2WWSA"
          - name: S3_SECRET_KEY
            value: "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"
